on: [push] # from : https://gist.github.com/benmarwick/4e239fcbd05db928e1b988a92fb32285

name: render all R Markdown documents 

jobs:
  render:
    name: render all R Markdown documents 
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@master
      - name: Install known depedencies  
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'knitr', 'devtools', 'here', 'tidyverse'))"
          Rscript -e "devtools::install_github('ThinkR-open/attachment')"
      - name: Install unknown depedencies 
        run: |
          Rscript -e "attachment::install_if_missing(attachment::att_from_rmds(path = '.'))"
      - name: render all R Markdown documents 
        run: |
          Rscript -e "lapply(fs::dir_ls('notebooks', glob='*.Rmd', recurse=TRUE), rmarkdown::render)"
      - name: Commit rendered files
        run: |
          git add notebooks/*
          git commit -m "Committing rendered files"
          git push origin master
